#!/bin/sh
set -e

if [ "$OS" = "Windows_NT" ]; then
	target="x86_64-pc-windows-msvc"
else
	case $(uname -sm) in
	"Darwin x86_64") target="x86_64-apple-darwin" ;;
	"Darwin arm64") target="aarch64-apple-darwin" ;;
	"Linux aarch64") target="aarch64-unknown-linux-gnu" ;;
	*) target="x86_64-unknown-linux-gnu" ;;
	esac
fi

jorin_uri="https://github.com/jorinai/jorin/releases/latest/download/jorin-${target}"
echo $jorin_uri
jorin_install_dir="$HOME/.jorin/bin"
exe="$jorin_install_dir/jorin"

if [ ! -d "$jorin_install_dir" ]; then
	mkdir -p "$jorin_install_dir"
fi

curl --fail --location --progress-bar --output "$exe.zip" "$jorin_uri"
chmod +x "$exe"

echo "Jorin was installed successfully to $exe"
if command -v jorin >/dev/null; then
	echo "Run 'jorin' to get started"
else
	case $SHELL in
	/bin/zsh) shell_profile=".zshrc" ;;
	*) shell_profile=".bashrc" ;;
	esac
	echo "Manually add the directory to your \$HOME/$shell_profile (or similar)"
	echo "  export PATH=\"\$jorin_install_dir:\$PATH\""

fi
echo
echo "Stuck? https://jorin.ai"
